workflows:
  ios-testflight:
    name: MASARSA iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: online.masarsa.app

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Create iOS project if missing
        script: |
          flutter create .

      - name: Set iOS bundle identifier
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier online.masarsa.app" ios/Runner/Info.plist

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration

      email:
        recipients:
          - alyamiali@hotmail.com
